# Generated by Django 3.0.5 on 2020-04-06 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='raspi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addr', models.CharField(max_length=255)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='controller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.FloatField()),
                ('humidity', models.FloatField()),
                ('lighting', models.IntegerField()),
                ('rel_1', models.BooleanField(default=False)),
                ('rel_2', models.BooleanField(default=False)),
                ('rel_3', models.BooleanField(default=False)),
                ('rel_4', models.BooleanField(default=False)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('raspi_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.raspi')),
            ],
        ),
    ]
